FILENAME: 303389.py, LINE: 17 (Too general exception)
